version: '3.7'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        depends_on:
          - php-fpm

    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        env_file:
          - .env
        environment:
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            TURBO_API_HOST: ${TURBO_API_HOST}
            TURBO_API_TOKEN: ${TURBO_API_TOKEN}
            TURBO_API_MODE: ${TURBO_API_MODE}
            AUTH_TOKEN: ${AUTH_TOKEN}
        volumes:
            - ./:/var/www
        depends_on:
          - mysql

    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
        environment:
          AUTH_TOKEN: ${AUTH_TOKEN}

    mysql:
        image: mysql:5.7
        volumes:
          - ./var/docker/mysql:/var/lib/mysql
          - ./var/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
           DB_USER: ${DB_USER}
           DB_PASSWORD: ${DB_PASSWORD}
           DB_NAME: ${DB_NAME}
        ports:
          - "33061:3306"